// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnUlZ7-JBAUUWH01Cbao-1Dm_orjAJt54',
    appId: '1:810819815260:web:e5d28b944f63dfdd6ea399',
    messagingSenderId: '810819815260',
    projectId: 'iotaquaapp',
    authDomain: 'iotaquaapp.firebaseapp.com',
    storageBucket: 'iotaquaapp.firebasestorage.app',
    measurementId: 'G-HK7F1WBH6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKU-jSEXoftXGq9653hJql7YWXG7_Rtr8',
    appId: '1:810819815260:android:10a3cf866a30ede16ea399',
    messagingSenderId: '810819815260',
    projectId: 'iotaquaapp',
    storageBucket: 'iotaquaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7eVlEeGi_iTcZYTfu01GKr_gBODaPyEs',
    appId: '1:810819815260:ios:8d67bcda67ea4fac6ea399',
    messagingSenderId: '810819815260',
    projectId: 'iotaquaapp',
    storageBucket: 'iotaquaapp.firebasestorage.app',
    iosBundleId: 'com.example.iotAquaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7eVlEeGi_iTcZYTfu01GKr_gBODaPyEs',
    appId: '1:810819815260:ios:8d67bcda67ea4fac6ea399',
    messagingSenderId: '810819815260',
    projectId: 'iotaquaapp',
    storageBucket: 'iotaquaapp.firebasestorage.app',
    iosBundleId: 'com.example.iotAquaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnUlZ7-JBAUUWH01Cbao-1Dm_orjAJt54',
    appId: '1:810819815260:web:0f2f38876fd0a06d6ea399',
    messagingSenderId: '810819815260',
    projectId: 'iotaquaapp',
    authDomain: 'iotaquaapp.firebaseapp.com',
    storageBucket: 'iotaquaapp.firebasestorage.app',
    measurementId: 'G-VECPZLH18F',
  );

}